spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/order_service
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always

  circuitbreaker:
    instances:
      inventory:

resilience4j:
  circuitbreaker:
    instances:

